CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE cloths (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    price double precision NOT NULL,
    description character varying(500),
    CONSTRAINT "PK_cloths" PRIMARY KEY (id)
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    passwordhash text NOT NULL,
    role character varying(50) NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE TABLE colors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    colorname character varying(50) NOT NULL,
    availiablestock integer NOT NULL,
    clothid integer NOT NULL,
    CONSTRAINT "PK_colors" PRIMARY KEY (id),
    CONSTRAINT "FK_colors_cloths_clothid" FOREIGN KEY (clothid) REFERENCES cloths (id) ON DELETE CASCADE
);

CREATE TABLE images (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    url character varying(500) NOT NULL,
    colorid integer NOT NULL,
    CONSTRAINT "PK_images" PRIMARY KEY (id),
    CONSTRAINT "FK_images_colors_colorid" FOREIGN KEY (colorid) REFERENCES colors (id) ON DELETE CASCADE
);

CREATE INDEX "IX_colors_clothid" ON colors (clothid);

CREATE UNIQUE INDEX "IX_images_colorid" ON images (colorid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250618112403_InitialPostgreSQL', '8.0.4');

COMMIT;

