CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE brands (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    price double precision NOT NULL,
    description character varying(500),
    CONSTRAINT "PK_brands" PRIMARY KEY (id)
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    passwordhash text NOT NULL,
    role character varying(50) NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    categoryname character varying(50) NOT NULL,
    availiableproduct integer NOT NULL,
    brandid integer NOT NULL,
    CONSTRAINT "PK_categories" PRIMARY KEY (id),
    CONSTRAINT "FK_categories_brands_brandid" FOREIGN KEY (brandid) REFERENCES brands (id) ON DELETE CASCADE
);

CREATE TABLE images (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    url character varying(500) NOT NULL,
    categoryid integer NOT NULL,
    CONSTRAINT "PK_images" PRIMARY KEY (id),
    CONSTRAINT "FK_images_categories_categoryid" FOREIGN KEY (categoryid) REFERENCES categories (id) ON DELETE CASCADE
);

CREATE INDEX "IX_categories_brandid" ON categories (brandid);

CREATE UNIQUE INDEX "IX_images_categoryid" ON images (categoryid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250618112403_InitialPostgreSQL', '8.0.4');

COMMIT;

